### ISSUE TITLE
problems after pressing full screen button

### ISSUE THREAD

**Issue by SanVerhavert** [d-pac/d-pac.client#50]
Debugging info
```json
{"now":"2014-11-05T14:42:20.963Z","url":"http://staging.tool.d-pac.be/assessors/#assess","version":"0.1.8","request":{"url":"/api/timelogs/545a37365264364363ee00f4","uuid":"bc2d2e37-e874-4ce2-8cbf-6488fd503a0b"},"userAgent":"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.111 Safari/537.36"}
```
actions: after looking at the tutorial I clicked Beoordeel], then I clicked on the full screen button of the first example.
problem: 1. only a part of the example was shown in the full screen (see image). Solved by scrolling.
               2. in the full screen, the + and - buttons weren't working.  They are working in normal screen.

The same is true with the second example.

![image](https://cloud.githubusercontent.com/assets/9549353/4919536/37574252-64fb-11e4-8194-da58db96aeec.png)

**Comment by creynders** [comment]
Appears to have been solved in IE11
