### ISSUE TITLE
One can log out while making a comparison without getting a kind request to finish the comparison

### ISSUE THREAD

**Issue by lcoertjens** [d-pac/d-pac.client#67]
when you are making a comparison and click on log out, you don't get the message. 
~~Moreover, (after about one second) I get the message "~~

~~Niet toegestaan! U bent niet (meer) ingelogd."~~
~~this appears strange, given I just requested to be logged out.~~

**Comment by creynders** [comment]
Extracted this:

>Moreover, (after about one second) I get the message "
>Niet toegestaan! U bent niet (meer) ingelogd."
>this appears strange, given I just requested to be logged out.

To a separate issue #83
