### ISSUE TITLE
the tool returns to the assignments page sometimes

### ISSUE THREAD

**Issue by SanVerhavert** [d-pac/d-pac.client#74]
```json
{"now":"2015-05-28T11:18:01.828Z","url":"http://staging.tool.d-pac.be/assessors/#assess","version":"0.4.0 (659)","request":{"url":"/api/phases","uuid":"54b01e53-47a5-4ceb-961d-c562c2df7c8f"},"userAgent":"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36"}
```

after hitting the download button on the select screen and then hitting back in the browser (see issue #73) the too returns to the assignments list (see screenshot).

![image](https://cloud.githubusercontent.com/assets/9549353/7858931/ae4d68dc-053c-11e5-8433-a7a31594b5e3.png)

**Comment by SanVerhavert** [comment]
on other times it returns to the "you have unfinished comparisons page".
![image](https://cloud.githubusercontent.com/assets/9549353/7858969/021d76fa-053d-11e5-97e4-a502baf97de5.png)

**Comment by creynders** [comment]
This is fixed, assessment selection screen is shown consistently now.
